import { applyKnowledgePrior } from '../knowledge/priors.js';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
function availability(p){if(['u','i','s'].includes(p.status))return clamp(n(p.chanceNext,25)/100,0,1);return clamp(n(p.chanceNext,100)/100,0,1);}
function fixtureFactor(diff,home){const map={1:1.20,2:1.10,3:1,4:.90,5:.80};return (map[diff]||1)*(home?1.03:.98);}
function matchupFactor(fixture,mode){const own=n(fixture?.teamStrength,0),opp=n(fixture?.opponentStrength,0);if(!own||!opp)return 1;const delta=(own-opp)/Math.max(1,(own+opp)/2);const sensitivity=mode==='attack'?.18:.14;return clamp(1+delta*sensitivity,.78,1.22);}
function minutesModel(p,seasonGames){const liveBase=n(p.v8BaseExpectedMinutes,NaN);if(Number.isFinite(liveBase)){const expected=clamp(liveBase,0,90)*availability(p);return {expected,confidence:clamp(n(p.v8MinutesConfidence,.5),.05,1),source:'v8-live'};}const mpg=n(p.minutes)/Math.max(1,seasonGames);const startsRate=n(p.starts)/Math.max(1,seasonGames);const priorMins=n(p.priorExpectedMinutes,NaN);let expected=clamp(.65*mpg+.35*(startsRate*82),0,90);if(Number.isFinite(priorMins)&&n(p.knowledgePriorWeight)>0)expected=(1-p.knowledgePriorWeight)*expected+p.knowledgePriorWeight*clamp(priorMins,0,90);expected*=availability(p);return {expected,confidence:clamp((expected/90)*(.65+.35*startsRate)+n(p.knowledgeConfidence)*n(p.knowledgePriorWeight)*.15,.05,1),source:'local'};}
function per90(v,p){return n(v)*90/Math.max(90,n(p.minutes));}
function sampledPer90(v,p,cap){const raw=clamp(per90(v,p),0,cap);const reliability=clamp(n(p.minutes)/450,0,1);return raw*reliability;}
export function projectionComponents(raw,fixture,{seasonGames=5}={}){const p=raw,mins=minutesModel(p,seasonGames),share=mins.expected/90,ff=fixtureFactor(fixture?.difficulty||3,fixture?.home),af=matchupFactor(fixture,'attack'),df=matchupFactor(fixture,'defence');const xgCap=p.position==='FWD'?1.25:p.position==='MID'?.9:.55,xaCap=p.position==='FWD'?.75:p.position==='MID'?.9:.65;const xg90=Number.isFinite(Number(p.xG90PriorAdjusted))?Number(p.xG90PriorAdjusted):sampledPer90(p.xG,p,xgCap),xa90=Number.isFinite(Number(p.xA90PriorAdjusted))?Number(p.xA90PriorAdjusted):sampledPer90(p.xA,p,xaCap),ppg=n(p.pointsPerGame),form=n(p.form);let appearance=share>=.67?2*share:share;let attack=0,defence=0,bonus=clamp(per90(p.bonus,p)*share,0,1.5),defCon=0;
 if(p.position==='GK'){attack=.2*xa90*share;defence=(1.7+.018*n(p.saves)/Math.max(1,seasonGames))*share;}
 if(p.position==='DEF'){attack=(4.8*xg90+3*xa90)*share;defence=1.75*share;defCon=clamp(n(p.defCon)/Math.max(1,seasonGames)*.16,0,1.3)*share;}
 if(p.position==='MID'){attack=(5*xg90+3*xa90)*share;defence=.55*share;defCon=clamp(n(p.defCon)/Math.max(1,seasonGames)*.14,0,1.25)*share;}
 if(p.position==='FWD'){attack=(4*xg90+3*xa90)*share;defCon=clamp(n(p.defCon)/Math.max(1,seasonGames)*.14,0,1.25)*share;}
 const formSignal=clamp((.55*ppg+.45*form)-4,-2.5,3)*.18*share;attack*=ff*af;defence*=fixture?.difficulty<=2?1.12:fixture?.difficulty>=4?.78:1;defence*=df;
 const rawExpected=clamp(appearance+attack+defence+bonus+defCon+formSignal,0,16);
 // Current-season sanity floor: an established, healthy starter with meaningful PL minutes
 // must not collapse to ~0 xP because one model component is sparse or temporarily missing.
 // The floor is deliberately conservative (58% of observed PPG, fixture-adjusted) and
 // disappears for low-minute/flagged players, so it cannot turn bench players into starters.
 const established=n(p.minutes)>=Math.max(270,seasonGames*50)&&n(p.starts)>=Math.ceil(seasonGames*.5);
 const healthy=!['i','u','s'].includes(String(p.status||'').toLowerCase())&&n(p.chanceNext,100)>=75;
 const empiricalPpg=Math.max(ppg,n(p.totalPoints)/Math.max(1,seasonGames));
 const empiricalFloor=established&&healthy?clamp(empiricalPpg*.58*clamp(ff,.82,1.16)*clamp(mins.expected/Math.max(60,n(p.minutes)/Math.max(1,seasonGames)),.65,1.15),0,9):0;
 const expected=clamp(Math.max(rawExpected,empiricalFloor),0,16);const uncertainty=clamp(2.4+(1-mins.confidence)*3.5+(fixture?.difficulty===3?.35:0)+n(p.knowledgePriorWeight)*.5,1.5,6);return {expected,expectedMinutes:mins.expected,minutesConfidence:mins.confidence,minutesSource:mins.source,fixtureFactor:ff,matchupFactors:{attack:af,defence:df},uncertainty,knowledgePriorWeight:n(p.knowledgePriorWeight),components:{appearance,attack,defence,bonus,defensiveContribution:defCon,form:formSignal,empiricalFloor}};}
export function projectPlayerGW(p,fixture,opts={}){return projectionComponents(p,fixture,opts);}
export function buildProjections(players,fixtures,currentGW,horizon=5,{knowledgeStore=null,season='2026-27'}={}){const teamFix=new Map();for(const f of fixtures){if(!f.gameweek||f.gameweek<=currentGW||f.gameweek>currentGW+horizon)continue;for(const [teamId,opp,home,difficulty,teamStrength,opponentStrength] of [[f.homeTeamId,f.awayTeamId,true,f.homeDifficulty,f.homeStrength,f.awayStrength],[f.awayTeamId,f.homeTeamId,false,f.awayDifficulty,f.awayStrength,f.homeStrength]]){const k=`${teamId}:${f.gameweek}`,arr=teamFix.get(k)||[];arr.push({opponentId:opp,home,difficulty,teamStrength,opponentStrength});teamFix.set(k,arr);}}const seasonGames=Math.max(1,currentGW);return players.map(raw=>{const knowledge=knowledgeStore?.get?.(season,raw.id);const p=knowledge?applyKnowledgePrior(raw,knowledge):raw;if(knowledge?.prior?.expectedMinutes!=null)p.priorExpectedMinutes=knowledge.prior.expectedMinutes;const weeks={},projectionDetail={};let total=0;for(let gw=currentGW+1;gw<=currentGW+horizon;gw++){const fs=teamFix.get(`${p.teamId}:${gw}`)||[];const ds=fs.map(f=>projectPlayerGW(p,f,{seasonGames}));const xp=ds.reduce((s,d)=>s+d.expected,0);weeks[gw]=xp;projectionDetail[gw]={expected:xp,uncertainty:Math.sqrt(ds.reduce((s,d)=>s+d.uncertainty**2,0)),fixtures:ds};total+=xp;}return {...p,projections:weeks,projectionDetail,projectedPoints:total};});}
