const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export function priorFeatures(rows,playerId,beforeGW){
 const xs=rows.filter(r=>n(r.element)===n(playerId)&&n(r.round??r.GW)<beforeGW).sort((a,b)=>n(a.round??a.GW)-n(b.round??b.GW));
 const recent=xs.slice(-4),sum=(arr,k)=>arr.reduce((s,r)=>s+n(r[k]),0),mins=sum(xs,'minutes');
 return {games:xs.length,minutes:mins,starts:sum(xs,'starts'),pointsPerGame:xs.length?sum(xs,'total_points')/xs.length:0,recentPoints:recent.length?sum(recent,'total_points')/recent.length:0,xG90:sum(xs,'expected_goals')*90/Math.max(90,mins),xA90:sum(xs,'expected_assists')*90/Math.max(90,mins),bonus90:sum(xs,'bonus')*90/Math.max(90,mins),defCon90:sum(xs,'defensive_contribution')*90/Math.max(90,mins),saves90:sum(xs,'saves')*90/Math.max(90,mins),startRate:xs.length?sum(xs,'starts')/xs.length:0,minutesPerGame:xs.length?mins/xs.length:0};
}
export function rowFeatures(r,prior){return [1,prior.pointsPerGame,prior.recentPoints,prior.xG90,prior.xA90,prior.bonus90,prior.defCon90,prior.saves90,prior.startRate,prior.minutesPerGame/90,r.was_home===true||String(r.was_home).toLowerCase()==='true'?1:0];}
function solve(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;[M[c],M[p]]=[M[p],M[c]];let d=M[c][c]||1e-9;for(let j=c;j<=n;j++)M[c][j]/=d;for(let r=0;r<n;r++)if(r!==c){const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j];}}return M.map(r=>r[n]);}
export function fitRidge(samples,lambda=8){if(!samples.length)return null;const k=samples[0].x.length,A=Array.from({length:k},()=>Array(k).fill(0)),b=Array(k).fill(0);for(const s of samples)for(let i=0;i<k;i++){b[i]+=s.x[i]*s.y;for(let j=0;j<k;j++)A[i][j]+=s.x[i]*s.x[j];}for(let i=1;i<k;i++)A[i][i]+=lambda;return solve(A,b);}
export function predictRidge(beta,x){return clamp(beta.reduce((s,v,i)=>s+v*x[i],0),0,18);}
export function walkForwardCalibrate(rows,{minGW=6,lambda=8}={}){const gws=[...new Set(rows.map(r=>n(r.round??r.GW)).filter(g=>g>=minGW))].sort((a,b)=>a-b),out=[];for(const gw of gws){const train=[],test=[];for(const r of rows){const rg=n(r.round??r.GW);if(rg<2||rg>gw)continue;const p=priorFeatures(rows,r.element,rg);if(!p.games)continue;const s={x:rowFeatures(r,p),y:n(r.total_points),position:r.position,gw:rg,playerId:r.element};(rg<gw?train:test).push(s);}for(const pos of ['GK','DEF','MID','FWD']){const tr=train.filter(s=>s.position===pos),te=test.filter(s=>s.position===pos);if(tr.length<30)continue;const beta=fitRidge(tr,lambda);for(const s of te)out.push({...s,predicted:predictRidge(beta,s.x),actual:s.y});}}return out;}
